name: Stock Scanner
on:
  schedule:
    - cron: '0 12 * * 1-5'  # 8:00 AM ET
  workflow_dispatch:

jobs:
  check-quota:
    runs-on: ubuntu-latest
    steps:
      - name: Check API Quota
        run: |
          curl "https://financialmodelingprep.com/api/v3/quota?apikey=${{ secrets.FMP_API_KEY }}" > quota.json
          cat quota.json
        
  scan-stocks:
    needs: check-quota
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas yfinance twilio
      - name: Run scanner
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
        run: python ./stock_scanner.py
